services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shift_manager_bot
    env_file:
      - .env
    restart: unless-stopped
    entrypoint: /app/entrypoint.sh
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    container_name: shift_manager_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${APP_POSTGRES_USER}
      POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD}
      POSTGRES_DB: ${APP_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -q"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db_data:
